blog/urls.py
__author__ = 'Andriy'


from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', 'blog.views.home', name='home'),
    url(r'^about/$', 'blog.views.about', name='about'),
    url(r'^articles/(?P<article_id>[0-9]+)/$', 'blog.views.show_article', name='article'),
    url(r'^contact/', 'blog.views.contact', name='contact'),
]

jsontest/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^pedometer/$', 'jsontest.views.pedometer', name=u'pedometer'),
    url(r'^timenow/$', 'jsontest.views.timenow', name=u'timenow'),
    url(r'^dailysteps/$', 'jsontest.views.daily_steps', name=u'dailysteps'),
    url(r'^dailysteps/(?P<day_id>[0-9]+)/$', 'jsontest.views.day_steps', name=u'daysteps'),
    url(r'^$', 'jsontest.views.home', name=u'home'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'blog.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^demo/', 'demo.views.home', name='home'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^jsontest/', include('jsontest.urls', namespace="jsontest")),
]





polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models


SHORT_TEXT_LEN = 500


class Article(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    user = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def get_short_text(self):
        if len(self.text) > SHORT_TEXT_LEN:
            return self.text[:SHORT_TEXT_LEN]
        else:
            return self.text

jsontest/models.py
from django.db import models


class Way(models.Model):
    steps = models.IntegerField(default=0)
    duration = models.IntegerField(default=0)


class DailySteps(models.Model):
    day = models.CharField(max_length=8)
    steps = models.IntegerField(default=0)

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render_to_response
from blog.models import Article, User


def index(request):
    return render(request, 'blog/index.html')


def home(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'blog/home.html', context)


def about(request):
    return render(request, 'blog/about.html')


def show_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    return render(request, 'blog/article.html', {'article': article})


def contact(request):
    user = User.objects.get(username='andriy')
    context = {
        'user': user,
    }
    return render(request, 'blog/contact.html', context)

demo/views.py
import platform
import pip

from django import get_version
from django.shortcuts import render


def home(request):
    """
    renders the deployment server details on the screen.
    :param request: The django formatted HttpRequest
    :return: renders context c with the demo template.
    """
    c = dict(python_version=platform.python_version(), django_version=get_version(), pip_version=pip.__version__)
    return render(request, 'demo/demo.html', c)

jsontest/views.py
import datetime

from django.core import serializers
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from jsontest.models import Way, DailySteps
from django.core.serializers.json import json, DjangoJSONEncoder


def home(request):
    if request.method == 'POST':
        # POST goes here . is_ajax is must to capture ajax requests. Beginners pit.
        if request.is_ajax():
            email = request.POST.get('email')
            password = request.POST.get('password')
            data = {"email": email, "password": password}
            return JsonResponse(data)
    # Get goes here
    return render(request, 'base_json.html')


@csrf_exempt
def pedometer(request):
    if request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        way = Way.objects.get(id=1)
        way.duration = body['duration']
        way.steps = body['steps']
        way.save()
        # mydict = {'date': datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S.%LZ')}
        mydict = {'steps': 1, 'duration': 1}
        nowdatetime = json.dumps(mydict)
        return JsonResponse(mydict)


def timenow(request):
    mydict = {'date': datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}
    return JsonResponse(mydict)


@csrf_exempt
def daily_steps(request):
    if request.method == 'GET':
        dailysteps = DailySteps.objects.all()
        data = []
        for day in dailysteps:
            data.append({'day': day.day, 'steps': day.steps})
        return JsonResponse(data, safe=False)
    elif request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        daysteps = DailySteps(day=body['day'], steps=body['steps'])
        daysteps.save()
        return JsonResponse({'result': 'ok'})


@csrf_exempt
def day_steps(request, day_id):
    if request.method == 'GET':
        daysteps = DailySteps.objects.get(day=day_id)
        return JsonResponse({'day': daysteps.day, 'steps': daysteps.steps})
    elif request.method == 'PUT':
        daysteps = DailySteps.objects.get(day=day_id)
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        daysteps.steps = body['steps']
        daysteps.save()
        return JsonResponse({'result': 'ok'})
    elif request.method == 'DELETE':
        daysteps = DailySteps.objects.get(day=day_id)
        daysteps.delete()
        return JsonResponse({'result': 'ok'})

mysite/views.py
from django.shortcuts import render

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import RequestContext, loader

from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}
About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>&copy; Sluka Andriy corp.</p>
{% endblock %}

blog/templates/blog/article.html
{% extends 'blog/base.html' %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block content %}

    <h1>{{ article.title }}</h1>
    <pre>{{ article.text }}</pre>

{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} &ndash; Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/journal/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog:home' %}">Blog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'blog:home' %}">Home</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="{% url 'blog:contact' %}">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container main-content">
        {% block content %}
        {% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block title %}
Contact
{% endblock %}

{% block content %}
    <h1>Contact</h1>
    <h4>{{ user.username }}</h4>

    <h6>{{ user.email }}</h6>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}

    <h1>Home</h1>

    {% for article in articles %}
        <h4><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a></h4>
{#        <h4><a href="/blog/articles/{{ article.id }}">{{ article.title }}</a></h4>#}
        <pre>{{ article.get_short_text }}</pre>
    {% endfor %}

{% endblock %}

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cerulean/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
{#    <link href="jumbotron.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>This is my websites</h1>
        <p></p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Blog</h2>
          <p>This is my 'Blog' app</p>
          <p><a class="btn btn-default" href="{% url 'blog:home' %}" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Polls</h2>
          <p>This is my 'Polls' app</p>
          <p><a class="btn btn-default" href="{% url 'polls:index' %}" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Demo</h2>
          <p>This is my 'Demo' app</p>
          <p><a class="btn btn-default" href="{% url 'home' %}" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

demo/templates/demo/demo.html
{% extends 'base.html' %}
{% block head %}
<title>Django on OpenShift</title>

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'
<link href="http://fonts.googleapis.com/css?family=Ubuntu:bold" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
{% load staticfiles %}
<link rel="stylesheet" href="{% static "demo/styles/style.css" %}"/>


<style>
    body{
        background: {% load staticfiles %} url("{% static "demo/images/image.jpeg" %}") fixed;
        background-size: cover;
        padding: 5px;
    }
</style>

{% endblock %}


{% block content %}
<header>

</header>
<div class="container">
    <div class="row-fluid">
	    <div class="welcome-box">
	    	<span id="welcome"> welcome
		    </span> <br>
	    	<span class="tagline">Django On OpenShift <br>
	    	<span class="main-version">
	    		v 2.0
	    	</span></span>
	    </div>

	    <div class="specs">
	    	<span class="spec-detail">
	    		Python version:
	    		<span class="version-number">
	    			{{ python_version }}
	    		</span>
                <br>

	    		Django version:

	    		<span class="version-number">
	    			{{ django_version }}
	    		</span>
	    	    <br>
	    		PIP version: &nbsp;

	    		<span class="version-number">
	    			  {{ pip_version }}
	    		</span>

	    	</span>
	    </div>
    </div>
</div>
<footer>
	a project maintained by  <a href="https://github.com/biwin"> biwin </a>.
</footer>
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"/>
    {% block head %}


    {% endblock %}



</head>
<body>
{% block content %}



{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    {% load staticfiles %}
    <script src="{% static 'demo/scripts/script.js' %}"></script>
</body>
</html>

templates/base_json.html
<!DOCTYPE html>

	<html>
	<head>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
	<link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
	</head>

	<body>

	  <div class="container">

	      <form class="form-signin" method="POST">
	      {% csrf_token %}
	        <h2 class="form-signin-heading">Enter Details</h2>
	        <label for="inputEmail" class="sr-only">Email address</label>
	        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
	        <label for="inputPassword" class="sr-only">Password</label>
	        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
	        <button id="submit" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	      </form>

	    </div>

	    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
 <script>
//For getting CSRF token
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
//For doing AJAX post
 $("#submit").click(function(e) {
    e.preventDefault();
    var csrftoken = getCookie('csrftoken');
    var email = $('#inputEmail').val();
    var password = $('#inputPassword').val();
//This is the Ajax post.Observe carefully. It is nothing but details of where_to_post,what_to_post

 $.ajax({
 url : window.location.href, // the endpoint,commonly same url
 type : "POST", // http method
 data : { csrfmiddlewaretoken : csrftoken,
 email : email,
 password : password
 }, // data sent with the post request
        // handle a successful response
        success : function(json) {
            console.log(json); // another sanity check
            alert('Hi   '+json['email'] +'!.' + '  You have entered password:'+ json['password']);
        },
        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
});
    </script>

</body>
</html>